### ISSUE TITLE
Napiprojekt.pl error

### ISSUE THREAD

**Issue by kruczek2011** [CaTzil/service.subtitles.napiprojekt#5]
Hey 
For start thanks for your work on Napiprojekt.pl addon. I can't use it thought because of this error shown in log.

﻿y): script successfully run
19:29:04 T:1760018504    INFO: Python script stopped
19:29:04 T:1760018504   DEBUG: Thread LanguageInvoker 1760018504 terminating
19:29:05 T:1766308808   DEBUG: Keyboard: scancode: 0x16, sym: 0x0113, unicode: 0x0000, modifier: 0x0
19:29:05 T:1766308808   DEBUG: bool CApplication::OnKey(const CKey&): right (0xf083) pressed, action is Right
19:29:06 T:1766308808   DEBUG: Keyboard: scancode: 0x14, sym: 0x0112, unicode: 0x0000, modifier: 0x0
19:29:06 T:1766308808   DEBUG: bool CApplication::OnKey(const CKey&): down (0xf081) pressed, action is Down
19:29:07 T:1766308808   DEBUG: Keyboard: scancode: 0x17, sym: 0x000d, unicode: 0x0000, modifier: 0x0
19:29:07 T:1766308808   DEBUG: bool CApplication::OnKey(const CKey&): return (0xf00d) pressed, action is Select
19:29:07 T:1766308808   DEBUG: New Service [service.subtitles.napiprojekt]
19:29:07 T:1753045048   DEBUG: bool XFILE::CPluginDirectory::StartScript(const string&, bool) - calling plugin Napiprojekt.pl('plugin://service.subtitles.napiprojekt/','4','?action=search&languages=English%2cPolish&preferredlanguage=Polish')
19:29:07 T:1753045048   DEBUG: bool XFILE::CPluginDirectory::WaitOnScriptResult(const string&, int, const string&, bool) - waiting on the Napiprojekt.pl (id=27) plugin...
19:29:07 T:1766768456  NOTICE: Thread LanguageInvoker start, auto delete: false
19:29:07 T:1766768456    INFO: initializing python engine.
19:29:07 T:1766768456   DEBUG: CPythonInvoker(27, /mnt/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/service.subj titles.napiprojekt/service.py): start processing
19:29:07 T:1766768456  NOTICE: -->Python Interpreter Initialized<--
19:29:07 T:1766768456   DEBUG: CPythonInvoker(27, /mnt/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/service.subtitles.napiprojekt/service.py): the source file to load is "/mnt/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/service.subtitles.napiprojekt/service.py"
19:29:07 T:1766768456   DEBUG: CPythonInvoker(27, /mnt/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/service.subtitles.napiprojekt/service.py): setting the Python path to /mnt/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/service.subtitles.napiprojekt:/:/mnt/asec/org.xbmc.kodi-1/pkg.apk/assets/python2.6/lib/python26.zip:/mnt/asec/org.xbmc.kodi-1/pkg.apk/assets/python2.6/lib/python2.6:/mnt/asec/org.xbmc.kodi-1/pkg.apk/assets/python2.6/lib/python2.6/plat-linux3:/mnt/asec/org.xbmc.kodi-1/pkg.apk/assets/python2.6/lib/python2.6/lib-tk:/mnt/asec/org.xbmc.kodi-1/pkg.apk/assets/python2.6/lib/python2.6/lib-old:/mnt/asec/org.xbmc.kodi-1/pkg.apk/assets/python2.6/lib/python2.6/lib-dynload
19:29:07 T:1766768456   DEBUG: CPythonInvoker(27, /mnt/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/service.subtitles.napiprojekt/service.py): entering source directory /mnt/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/service.subtitles.napiprojekt
19:29:07 T:1766768456   DEBUG: CPythonInvoker(27, /mnt/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/service.subtitles.napiprojekt/service.py): instantiating addon using automatically obtained id of "service.subtitles.napiprojekt" dependent on version 2.14.0 of the xbmc.python api
19:29:08 T:1940325952   DEBUG: CurlFile::Open(0x701f6010) https://r2---sn-2apm-f5fz.googlevideo.com/videoplayback?requiressl=yes&shardbypass=yes&cmbypass=yes&id=6285b810ca662dd1&itag=22&source=picasa&ip=78.8.229.195&ipbits=0&expire=1433065735&sparams=cmbypass,expire,id,ip,ipbits,itag,mm,mn,ms,mv,pl,requiressl,shardbypass,source&signature=4CA00EE3B44DF8BF998D73F280C7D59B5167FBEE.5A5FA9D982D4E976CE08C96A3C4EE8FBFA8CA185&key=cms1&cms_redirect=yes&mm=31&mn=sn-2apm-f5fz&ms=au&mt=1431538055&mv=m&pl=19
19:29:23 T:1766768456   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'str' object has no attribute 'hexdigest'
                                            Traceback (most recent call last):
                                              File "/mnt/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/service.subtitles.napiprojekt/service.py", line 224, in <module>
                                                Search(item)
                                              File "/mnt/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/service.subtitles.napiprojekt/service.py", line 94, in Search
                                                "f": d.hexdigest(),
                                            AttributeError: 'str' object has no attribute 'hexdigest'
                                            -->End of Python script error report<--
19:29:23 T:1766768456    INFO: CPythonInvoker(27, /mnt/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/service.subtitles.napiprojekt/service.py): waiting on thread 1940325952
19:29:23 T:1766308808   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
19:29:27 T:1766768456    INFO: Python script stopped
19:29:27 T:1766768456   DEBUG: Thread LanguageInvoker 1766768456 terminating
19:29:27 T:1753045048   DEBUG:  bool XFILE::CPluginDirectory::WaitOnScriptResult(const string&, int, const string&, bool) - plugin exited prematurely - terminating
19:29:27 T:1753045048   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://service.subtitles.napiprojekt/?action=search&languages=English%2cPolish&preferredlanguage=Polish
19:29:28 T:1766308808   DEBUG

I have already change duration time from 15 to 30 and still doesn't work.
Help:-)

**Comment by CaTzil** [comment]
Its probably not suppprts streaming, cause the site works with file hash signature, so the addon tries to calculate one from something wrong...

**Comment by kruczek2011** [comment]
So you are saying that I can't use this addon,for example, with Genesis addon?

**Comment by CaTzil** [comment]
Exactly, try that... https://github.com/CaTzil/service.subtitles.napisy24pl
