### ISSUE TITLE
Subtitle file contains only text "brak pliku tymczasowego"

### ISSUE THREAD

**Issue by rob006** [CaTzil/service.subtitles.napiprojekt#6]
A few days ago plugin stopped working properly. Plugin finds subtitles but after downloading the file contains only text "brak pliku tymczasowego".

**Comment by CaTzil** [comment]
Yeah, i see that they changed the site.
Will look at that.

**Comment by rob006** [comment]
I tried QNapi v0.1.5 and it's work fine. You can try figure out how they download subtitles: https://github.com/QNapi/qnapi

**Comment by CaTzil** [comment]
I`ve tried that, https://github.com/kozervar/napi-js/blob/master/napi-js.js
and it much simpler...

**Comment by CaTzil** [comment]
BTW, According to QNapi source code, the current api works, and i managed to bypass there restrictions, the only thing that left is to open the encrypted zip file (I have the password from QNapi)...

**Comment by CaTzil** [comment]
OK, found a working way...Will release update soon.

**Comment by CaTzil** [comment]
bccf26ec505216f1bd51c2cb9c1a167a52cb3af6 Fixes the download issue.

**Comment by rob006** [comment]
:thumbsup:
