### ISSUE TITLE
Problem with polish characters in directory/file name

### ISSUE THREAD

**Issue by BarretNT** [CaTzil/service.subtitles.napiprojekt#8]
At beggining sorry for my bad english.

I have all movies in my collection in separate directories. 
Each directory contain 1 movie. 
Directory name is as follows Polish title - Original Title [year of premiere] for example
Nowy Początek - Arrival [2016]. When i have polish characters in directory of file name napiproject wont find any subtitles, but when i change polish characters to plain ascii (like this Nowy Poczatek - Arrival [2016]) napiprojekt will find and download subtitles. 

Is it possible to fixit? Some time ago this works fine.  I dont want to rename all directory and files names in collection.

**Comment by CaTzil** [comment]
I will look into it.
Thanx for the report

**Comment by BarretNT** [comment]
Any progress?

**Comment by CaTzil** [comment]
Hi,
Not yet... will do soon.
