### ISSUE TITLE
Enhancement: Preferred subtitle language

### ISSUE THREAD

**Issue by kokosowy** [CaTzil/service.subtitles.napiprojekt#9]
Hi!

I wonder whether you could make small enhancement. As for now while listing available subtitles for download, on top is not the proffered subtitle language (there is a setting in Kodi for that).

Example of settings:
Preferred language: Polish
Other languages: English

List of subtitles for download:
English
English
English
Polish
Polish
Polish
Polish

I wonder whether it could be sorted this way so the preferred language would be always on top of the list. It will help with auto-downloading the subs just while starting the video (there is a plugin/script for it and unfortunately it always download the subtitle from the top of the list) and also for regular download it will help much as preferred language would be on top right away.

Thank you,
K

**Comment by CaTzil** [comment]
@kokosowy can u check that it solved the issue?

**Comment by kokosowy** [comment]
Strange.. I've downloaded release v1.1.1, installed it, restarted Kodi, ensured I got right language preferences.. But still I can't see any difference. English subs are still on top of the list to download.. Any ideas?

**Comment by CaTzil** [comment]
Maybe https://github.com/CaTzil/service.subtitles.napiprojekt/blob/83d72051fd47875a769862b9f30d8abf037a8775/resources/lib/NapiProjekt.py#L36 should not be reversed

**Comment by CaTzil** [comment]
Can you change that `reverse` flag, and check at ur system?
I don`t have videos that are on that service, so i can`t check that :\

**Comment by kokosowy** [comment]
Hi CaTzil, any hint where is this flag to find?

**Comment by CaTzil** [comment]
CaTzil/service.subtitles.napiprojekt/blob/master/resources/lib/NapiProjekt.py#L36
